day09/musicians/urls.py
from django.urls import path
from . import views

app_name = "musicians"

urlpatterns=[
    # u - v - t 순서 고정.
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    # django가 지정한 경로 작성 방식
    # <데이터 타입 : 변수 명>
    # 실제 사용자가 작성하는 url
    path('<int:musician_pk>/', views.detail, name="detail"),
    path('<int:pk>/delete/', views.delete, name="delete"),
    path('<int:pk>/edit/', views.edit, name="edit"),
    path('<int:musician_pk>/create_album/', views.create_album, name="create_album"),
    path('<int:musician_pk>/delete_album/<int:album_pk>/', views.delete_album, name="delete_album"),
]

day09/review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('musicians/', include('musicians.urls')),
]

day09/musicians/models.py
from django.db import models

# Create your models here.
# 객체 생성 -> 테이블 명
class Musician(models.Model):
    # 멤버 변수
    name = models.CharField(max_length=100)
    age = models.IntegerField()

    # 인스턴스 호출 시 출력 내용 덮어쓰기(=toString())
    def __str__(self):
        return f'{self.name} : {self.age}'

class Album(models.Model):
    musician = models.ForeignKey(to=Musician, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    release_date = models.DateField()

day09/musicians/forms.py
# 장고에서 미리 정의해둔 forms 받아오기
from django import forms
from .models import Musician, Album

# 클래스 정의
class MusicianForm(forms.ModelForm):
    # 쿨래스에 대한 클래스
    class Meta:
        # 어떤 모델? Musician에 정의된 것
        model = Musician
        # 모델에 있는 모든 필드 불러오기...
        fields = '__all__'

class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        exclude = ['musician']

day09/musicians/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from .forms import MusicianForm, AlbumForm
from .models import Musician, Album

# Create your views here.
def index(request):
    # .all()로 조회하면 QuerySet
    # QuerySet은 list처럼 사용 가능
    musicians = Musician.objects.all()
    context = {
        'musicians' : musicians
    }
    return render(request, "musicians/index.html", context)

def create(request):
    if request.method == "POST" :
        # 사용자의  요청 정보를 담아준다.
        form = MusicianForm(request.POST)
        # forms를 상속받았기 때문에 사용가능
        if form.is_valid():
            # Musician가 models에게 받은 메서드
            # ModelForm을 정의할 때 class Meta : Musician을 담아줬다.
            musician = form.save()
            return redirect('musicians:index')
    else :
        # MusicianForm 불러오기
        # form은 MusicianForm 인스턴스
        # MusicianForm이 가진 정보를 가짐.
        # MusicianForm은 Musician의 정보를 들고 있음
        # template에서 보여줄 tag 정보도 갖고 있다 => modelForm이 하는 일
        form = MusicianForm()
    context = {
        'form' : form
    }
    return render(request, "musicians/create.html", context)

# 함수이름(urls에 작성한 변수명)
def detail(request, musician_pk):
    musician = Musician.objects.get(pk=musician_pk)
    albums = Album.objects.filter(musician_id=musician_pk)
    album_form = AlbumForm()
    context = {
        'musician' : musician,
        'albums' : albums,
        'album_form' : album_form
    }
    return render(request, 'musicians/detail.html', context)

def edit(request, pk):
    musician = Musician.objects.get(pk=pk)
    if request.method == "POST" :
        form = MusicianForm(request.POST, instance=musician)
        if form.is_valid():
            form.save()
            return redirect('musicians:detail', musician.pk)
    else :
        form = MusicianForm(instance=musician)
    context= {
        'form' : form
    }
    return render(request, 'musicians/edit.html', context)

@require_POST
def delete(request, pk):
    Musician.objects.get(pk=pk).delete()
    return redirect('musicians:index')

@require_POST
def create_album(request, musician_pk):
    form = AlbumForm(request.POST)
    album = form.save(commit=False)
    album.musician_id = musician_pk
    album.save()
    return redirect('musicians:detail', musician_pk)

@require_POST
def delete_album(request, musician_pk, album_pk):
    Album.objects.get(pk=album_pk).delete()
    return redirect('musicians:detail', musician_pk)

day09/musicians/templates/musicians/create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>create</title>
</head>
<body>
  <h1>글 생성</h1>
  <hr>
  <!-- action을 비워두면 현재 위치로 요청 -->
  <!-- 차이점 : method를 지정해준 것과 안해준 것의 차이 -->
  <form action="" method="POST">
    {% csrf_token %}
    {# views에서 context에 담아 넘겨준 form #}
    {{form}}
    <input type="submit" value="제출">
  </form>
</body>
</html>

day09/musicians/templates/musicians/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>detail</title>
</head>
<body>
  <h1>상세 페이지</h1>
  <hr>
  <h1>{{musician}}</h1>
  <hr>
  <p>{{musician.name}}</p>
  <p>{{musician.age}}</p>
  <hr>
  <button><a href="{% url 'musicians:index' %}">목록</a></button>
  <button><a href="{% url 'musicians:edit' musician.pk %}">수정</a></button>
  <form action="{% url 'musicians:delete' musician.pk %}" method="post">
    {% csrf_token %}
    <input type="submit" value="삭제">
  </form>
  <hr>
  <h2>발매된 앨범 정보</h2>
  <hr>
  <ul>
    {% for album in albums %}
    <li>
      {{album.musician.name}} - {{album.title}}
      <form action="{% url 'musicians:delete_album' musician.pk album.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" value="삭제">
      </form>
    </li>
    {% empty %}
      <p>앨범이 없습니다.</p>
    {% endfor %}
  </ul>
  <form action="{% url 'musicians:create_album' musician.pk %}" method="post">
    {% csrf_token %}
    {{album_form}}
    <input type="submit" value="앨범 등록">
  </form>
</body>
</html>

day09/musicians/templates/musicians/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>edit</title>
</head>
<body>
  <h1>수정 페이지</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="수정">
  </form>
</body>
</html>

day09/musicians/templates/musicians/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>index</title>
</head>
<body>
  <h1>메인 페이지</h1>
  <hr>
  <button><a href="{% url 'musicians:create' %}">추가</a></button>
  <hr>
  <ul>
    {% for musician in musicians %}
      <a href="{% url 'musicians:detail' musician.pk %}"><li>{{musician}}</li></a>
    {% endfor %}
  </ul>
</body>
</html>