day05/articles/urls.py
from django.urls import path
from . import views
app_name = "articles"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('new/', views.new_write, name="new"),
    path('create/', views.create, name="create"),
    path('introduce/', views.introduce, name="introduce"),
    path('detail/<int:pk>', views.detail, name="detail"),
    path('delete/<int:pk>', views.delete, name="delete"),
    path('<int:pk>/edit', views.edit, name="edit"),
    path('<int:pk>/update', views.update, name="update"),
]

day05/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model) : # articles_article
    title = models.CharField(max_length=150)                # 글자수를 제한하고 싶을 때 사용
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)    # 자동으로 처음 생성된 시간을 넣어주겠다
    updated_at = models.DateTimeField(auto_now=True)        # 글이 생성(=수정)되는 시간을 넣어주겠다
    # boolean - models.BooleanField(blank=True)

    # 매직 메서드 java의 toString()과 같은 역할 
    def __str__(self) :
        return f'{self.id}번째 글 - {self.title} : {self.content}'

day05/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.

def index(request) :
    articles = Article.objects.all()
    context = {
        'articles' : articles
    }
    
    return render(request, 'articles/index.html', context)

def new_write(request) :
    return render(request, 'articles/new.html')

def create(request) :
    title = request.POST.get('title')
    content = request.POST.get('content')
    Article.objects.create(title=title, content=content)
    
    return redirect('articles:index')

def introduce(request) :
    context = {
        'name' : '이영주', 
        'age' : '28'
    }
    return render(request, 'articles/introduce.html', context)

def detail(request, pk) :
    article = Article.objects.get(pk=pk)

    context = {
        'article' : article
    }

    return render(request, 'articles/detail.html', context)

def delete(request, pk) :
    # request.method
    
    Article.objects.get(pk=pk).delete()
    return redirect('articles:index')

def edit(request, pk) :
    article = Article.objects.get(pk=pk)
    context = {
        'article' : article
    }
    return render(request, 'articles/edit.html', context)

def update(request, pk) :
    article = Article.objects.get(pk=pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect('articles:detail', pk)

day05/articles/templates/articles/create.html
{% extends 'base.html' %}
{% block body %}
  <h1>글 작성 결과</h1>
  <hr>
  <table style="width: 400px; height: 100px;">
    <tr>
      <th style="border: 1px solid black;">제목</th>
      <th style="border: 1px solid black;">내용</th>
    </tr>
    <tr>
      <td style="border: 1px solid black;">{{title}}</td>
      <td style="border: 1px solid black;">{{content}}</td>
    </tr>
  </table>
  <a href="{% url 'articles:index' %}">back</a>
{% endblock %}

day05/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block body %}
<h1>글 세부 정보</h1>
<hr>
<h3>{{article.pk}}</h3>
<p>작성 시간: {{article.created_at}}</p>
<h4>글 제목 : {{article.title}}</h4>
<h5>글 내용 : {{article.content}}</h5>
<hr>
<h6><a href="{% url 'articles:edit' article.pk %}">수정</a></h6>
<a href="{% url 'articles:index' %}">BACK</a>
{% endblock %}

day05/articles/templates/articles/edit.html
{% extends 'base.html' %}
{% block body %}
<h1>글 수정</h1>
<hr>
<form action="{% url 'articles:update' article.pk %}" method="POST">
  {% csrf_token %}
  <label for="la_t">글 제목 : </label>
  <input type="text" name="title" id="la_t" value="{{article.title}}">
  <label for="la_c">글 내용 : </label>
  <input type="text" name="content" id="la_c" value="{{article.content}}">
  <br>
  <input type="submit" value="수정" style="width: 150px; margin: 10px 80px;">
</form>
{% endblock %}

day05/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block body %}
<h1>게시판</h1>
<hr>
{% for article in articles %}
<h4>{{article.pk}}번째 글</h4>
<h5><a href="{% url 'articles:detail' article.pk %}" >{{article.title}}</a></h5>
<h6><a href="{% url 'articles:delete' article.pk %}">삭제</a></h6>
<hr>
{% endfor %}
<hr>
<a href="{% url 'articles:new' %}">NEW</a>
<br>
<a href="{% url 'articles:introduce' %}">INTRO</a>
{% endblock %}

day05/articles/templates/articles/introduce.html
{% extends 'base.html' %}
{% block body %}
  <h1>INTRO</h1>
  <hr>
  <p>{{name}}</p>
  <p>{{age}}</p>
  <a href="{% url 'articles:index' %}">back</a>
{% endblock %}

day05/articles/templates/articles/new.html
{% extends 'base.html' %}
{% block body %}
  <h1>글 작성 페이지</h1>
  <hr>
  <form action="{% url 'articles:create' %}" method="POST">
    {# 사이트 간 요청 위조 #}
    {% csrf_token %}
    <label for="la_title"> 글 제목 : </label>
    <input type="text" name="title" id="la_title">
    <br>
    <label for="la_content">글 내용 : </label>
    <input type="text" name="content" id="la_content">
    <br>
    <input type="submit" value="등록" style="width: 150px; margin: 10px 80px;">
  </form>
{% endblock %}