django_relation/accounts/urls.py
# accounts의 urls
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.password, name="password"),
    path('follow/<int:user_pk>/', views.follow, name="follow"),
    # username을 찾는 로직이 사용되는 경우 이 경로가 제일 위에 있으면
    # "login/", "logout/" 같은 경로를 찾을 때 username으로 인식하기 때문에 해당 경로에 접근할 수 없다
    # 그렇기 때문에 제일 아래에 경로를 설정해야 한다.
    path('<str:username>/', views.profile, name="profile"),
]

django_relation/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:article_pk>/update/', views.update, name="update"),
    path('<int:article_pk>/', views.detail, name="detail"),
    path('<int:article_pk>/delete/', views.delete, name="delete"),
    path('<int:article_pk>/comment_create/', views.comment_create, name="comment_create"),
    path('<int:article_pk>/comment_delete/<int:comment_pk>/', views.comment_delete, name="comment_delete"),
    path('<int:article_pk>/like/', views.like, name="like"),
    path('<int:article_pk>/recommend/', views.recommend, name="recommend"),
]

django_relation/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_relation/articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail
from django.contrib.auth import get_user_model

# Create your models here.

def articles_image_path(instance, filename):
    return f'user_{instance.user.pk}/{filename}'

def get_sentinel_user():
    return get_user_model().objects.get_or_create(username='deleted')[0]

class Article(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # blank는 유효성 검사 시
    # null은 db 컬럼의 null
    image = models.ImageField(blank=True, upload_to=articles_image_path)
    #upload_to="%y/%m/%d/" 이건 이미지를 날짜 별로 저장하겠다는 의미
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[Thumbnail(width=200, height=300)],
        format='JPEG',          # 가장 저용량이면서 화질이 좋음
        options={'quality': 90} # 90은 %
    )
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE,
    )
    like_users = models.ManyToManyField(
        to=settings.AUTH_USER_MODEL, 
        related_name='like_articles',
        blank=True
    )
    recommenders = models.ManyToManyField(
        to=settings.AUTH_USER_MODEL,
        related_name='recommend_articles',
        blank=True
    )

    def __str__(self):
        return f"{self.pk}번째 글, {self.title} - {self.content}"

class Comment(models.Model):
    article = models.ForeignKey(
        to=Article, 
        on_delete=models.CASCADE)
        # related_name='comments')
    content = models.CharField(max_length=200)
    create_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return f"Article: {self.article}, {self.pk} - {self.content}"

django_relation/articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        exclude = ['user', 'like_users', 'recommenders']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # fields = '__all__'
        # article만 제외하고 넘기겠다
        exclude = ['article', 'user']

django_relation/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from IPython import embed
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import JsonResponse

# Create your views here.
def index(request):
    # embed()
    articles = Article.objects.all()
    # 1. Paginator(전체 리스트, 한 페이지당 갯수)
    paginator = Paginator(articles, 3)
    # 2. 몇 번째 페이지를 보여줄 것인지 GET으로 받기
    # 'articles/?page=3'
    page = request.GET.get('page')
    # 해당하는 페이지의 게시글만 가져오기
    articles = paginator.get_page(page)
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    # 1은 N을 보장할 수 없기 때문에 QuerySet(comment_set)형태로 조회해야 한다.
    comments = article.comment_set.all()
    comment_form = CommentForm()
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments
    }
    return render(request, 'articles/detail.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user_id = request.user.pk
            article.save()
            messages.success(request, '게시물 작성 완료')
            return redirect('articles:detail', article.pk)
        else:
            messages.error(request, '잘못된 데이터') # 잘못된 항목을 넣었다
    else:
        form = ArticleForm()
    context = {
        'form': form
    }
    return render(request, 'articles/form.html', context)

@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if article.user == request.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                article = form.save()
                return redirect('articles:detail', article.pk)
            else:
                return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
    context = {
        'form': form
    }
    return render(request, 'articles/form.html', context)

@login_required
@require_POST
def delete(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if article.user == request.user:
        article.delete()
    else:
        pass
    return redirect('articles:index')

@login_required
@require_POST
def comment_create(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    form = CommentForm(request.POST)
    if form.is_valid() :
        comment = form.save(commit=False)
        comment.article_id = article_pk
        comment.user = request.user
        comment.save()
        return redirect('articles:detail', article_pk)
    else:
        context = {
            'form' : form,
            'article' : article
        }
    return redirect('article:detail', context)

@login_required
@require_POST
def comment_delete(request, article_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    comment.delete()
    return redirect('articles:detail', article_pk)

@login_required
def like(request, article_pk):
    # 특정 게시물에 대한 정보
    article = get_object_or_404(Article, pk=article_pk)
    # 좋아요를 누른 유저에 대한 정보
    user = request.user

    # 사용자가 게시글의 좋아요 목록에 있으면
    if user in article.like_users.all():
        article.like_users.remove(user)
        liked = False
    else:
        article.like_users.add(user)
        liked = True

    context = {
        'liked': liked,
        'count': article.like_users.count(),
    }

    return JsonResponse(context)

@login_required
def recommend(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    user = request.user

    if user in article.recommenders.all():
        article.recommenders.remove(user)
    else:
        article.recommenders.add(user)

    return redirect('articles:index')

django_relation/articles/templates/articles/_comment.html
<i class="far fa-comment" style="display: inline-block;  margin-left: 10px;"></i>
<p style="display: inline-block;">{{comments|length}}</p>

django_relation/articles/templates/articles/_like.html
{% if user in article.like_users.all %}
<i class="fas fa-heart fa-md like-button" data-id="{{article.id}}" style="display: inline-block; color: crimson;"></i>
{% else %}
<i class="far fa-heart fa-md like-button" data-id="{{article.id}}" style="display: inline-block; color: black;"></i>
{% endif %}
<span class="like-count-{{article.id}}" style="display: inline-block;">{{ article.like_users.count }}</span>

django_relation/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<h1>상세 페이지</h1>
<hr>
<p>{{ article.pk }}번째 글</p>
<h2>{{ article.title }}</h2>
<h3>{{ article.content }}</h3>
{% if article.image %}
<img src="{{ article.image_thumbnail.url }}" alt="article.image">
{% endif %}
<h3>작성자: {{ article.user.username }}</h3>
<hr>
<p>{{comments|length}}개의 댓글</p>
<!-- <p>{{article.comment_set.all|length}}개의 댓글</p> -->
<ul>
  {% for comment in comments %}
  <li>
    {{comment.content}}
    <!-- 2개 이상의 값을 넘겨주고자 할 때 순서 주의 -->
    {% if comment.user == request.user %}
    <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method="post">
      {% csrf_token %}
      <input type="submit" value="댓글 삭제">
    </form>
    {% endif %}
  </li>
  {% empty %}
  <p>등록된 댓글이 없습니다.</p>
  {% endfor %}
</ul>
<hr>
<form action="{% url 'articles:comment_create' article.pk %}" method="POST">
  {% csrf_token %}
  {{comment_form}}
  <input type="submit" value="댓글 생성">
</form>
<hr>
{% if article.user == request.user %}
<a href="{% url 'articles:update' article.pk %}">[UPDATE]</a>
<form action="{% url 'articles:delete' article.pk %}" method="POST">
  {% csrf_token %}
  <input type="submit" value="DELETE" class="btn btn-primary">
</form>
{% endif %}
<a href="{% url 'articles:index' %}">[back]</a>
<script src="{% static '/articles/js/like.js' %}"></script>
{% endblock %}

django_relation/articles/templates/articles/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% if request.resolver_match.url_name == 'create' %}
  <h1>글 생성</h1>
{% else %}
  <h1>글 수정</h1>
{% endif %}

<hr>
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
  {% endbuttons %}
</form>

  <a href="{% url 'articles:index' %}">[BACK]</a>

{% endblock %}

django_relation/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
  <style>
    .fix-image {
      width: 100%;
      height: auto;
      max-height: 300px;
      object-fit: contain;
    }
    /* .responsive {
    padding: 0 6px;
    float: left;
    width: 24.99999%;
  }
  
  @media only screen and (max-width: 300px) {
    .responsive {
      width: 49.99999%;
      margin: 6px 0;
    }
  }
  
  @media only screen and (max-width: 200px) {
    .responsive {
      width: 100%;
    }
  } */
  </style>
<!-- <p>{{username}}님 반갑습니다.</p> -->
<div class="row responsive">

  {% for article in articles %}
  <div class="col-4">

    <div class="card">
      {% if article.image %}
      <img src="{{ article.image_thumbnail.url }}" class="card-img-top fix-image" alt="{{article.image}}">
      {% else %}
      <img src="{% static '/articles/images/unnamed.jpg' %}" class="card-img-top fix-image" alt="unnamed">
      {% endif %}
      <div class="card-body">
        <h5 class="card-title">{{ article.title }}</h5>
        <a class="card-text" href="{% url 'accounts:profile' article.user.username %}">{{ article.user.username }}</a>
        {% include 'articles/_like.html' %}
        {% include 'articles/_comment.html' %}
        <br>
        <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">DETAIL</a>
      </div>
    </div>
    <!-- {% if user in article.recommenders.all %}
      <a href="{% url 'articles:recommend' article.pk %}">추천 취소</a>
      {% else %}
      <a href="{% url 'articles:recommend' article.pk %}">추천</a>
      {% endif %} -->
  </div>
  {% endfor %}
</div>
<hr>
<ul>
  {% for num in articles.paginator.page_range %}
    <a href="{% url 'articles:index' %}?page={{ num }}">{{ num }}</a>
  {% endfor %}
</ul>
<script src="{% static '/articles/js/like.js' %}"></script>
{% endblock %}