django_relation/accounts/urls.py
# accounts의 urls
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.password, name="password"),
    path('follow/<int:user_pk>/', views.follow, name="follow"),
    # username을 찾는 로직이 사용되는 경우 이 경로가 제일 위에 있으면
    # "login/", "logout/" 같은 경로를 찾을 때 username으로 인식하기 때문에 해당 경로에 접근할 수 없다
    # 그렇기 때문에 제일 아래에 경로를 설정해야 한다.
    path('<str:username>/', views.profile, name="profile"),
]

django_relation/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:article_pk>/update/', views.update, name="update"),
    path('<int:article_pk>/', views.detail, name="detail"),
    path('<int:article_pk>/delete/', views.delete, name="delete"),
    path('<int:article_pk>/comment_create/', views.comment_create, name="comment_create"),
    path('<int:article_pk>/comment_delete/<int:comment_pk>/', views.comment_delete, name="comment_delete"),
    path('<int:article_pk>/like/', views.like, name="like"),
    path('<int:article_pk>/recommend/', views.recommend, name="recommend"),
]

django_relation/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_relation/mysite/templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% bootstrap_css %}
  <title>Document</title>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      {% if user.is_authenticated %}
      <a class="navbar-brand" href="{% url 'accounts:profile' user.username %}">Hi! {{ user.username }}</a>
      {% else %}
      <a class="navbar-brand" href="#">로그인을 해주세요. </a>
      {% endif %}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <!-- <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a> -->
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'articles:create' %}">게시글 등록</a>
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
            <a class="nav-item nav-link" href="{% url 'accounts:update' %}">정보 수정</a>
            <form action="{% url 'accounts:delete' %}" method="post">
              {% csrf_token %}
              <input class="btn btn-secondary" type="submit" value="회원탈퇴">
            </form>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}">로그인</a>
          {% endif %}
          <!-- <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> -->
        </div>
      </div>
    </nav>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags}}">{{ message.message }}</div>
      {% endfor %}
    {% endif %}
    <hr>
    {% block body %}
    {% endblock %}
  </div>
  {% bootstrap_javascript jquery='full' %}
  <script src="https://kit.fontawesome.com/176b34b7db.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
</body>
</html>